### ISSUE TITLE
Enable CORS?

### ISSUE THREAD

**Issue by gribnoysup** [samjbmason/punkapi-server#2]
Hi @samjbmason! This is not an issue, more like a proposal. How do you feel about [enabling CORS](http://enable-cors.org/) on punkapi.com? I see that you are using express, so enabling CORS will be as easy as adding [express cors module](https://github.com/expressjs/cors) to your index.js

Anyway, great work with collecting all this data in one place, thank you a lot!

**Comment by samjbmason** [comment]
That's a really great idea. Definitely an oversight on my part. I will do that over the next few days.

**Comment by samjbmason** [comment]
I have just deployed an update to the api that now enables CORS. Let me know if everything works as you hope. 👍

**Comment by gribnoysup** [comment]
Yay! Working brilliantly, thank you!
